# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatappui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rasucontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cf0d79eeb5944771b32c8a62bd29ee0b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_685716746e534507a52478d2df80bd8e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rasucontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cf0d79eeb5944771b32c8a62bd29ee0b }}/chatappui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatappui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_01886e5a91f1437198b62540f199cf29 }}
        images: 'rasucontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cf0d79eeb5944771b32c8a62bd29ee0b }}/chatappui:${{ github.sha }}'